### ISSUE TITLE
Windows: cloxp will not start

### ISSUE THREAD

**Issue by mmeroberts** [cloxp/cloxp-install#10]
Firstly the install was not working then the start.cmd did no work, but if I run the commands individually I get the following:

PS C:\Users\MartinRoberts\cloxp-0.2.0\LivelyKernel> node bin\lk-server.js --lk-dir C:\Users\MartinRoberts\cloxp-0.2.0\LivelyKernel --db-config "{\"enableRewriting\":false}"
Checking if PartsBin exists...
...yes
C:\Users\MartinRoberts\cloxp-0.2.0\LivelyKernel\node_modules\lively-loader\index.js:155
  livelyLang.deprecatedLivelyPatches();
             ^

TypeError: livelyLang.deprecatedLivelyPatches is not a function
    at start (C:\Users\MartinRoberts\cloxp-0.2.0\LivelyKernel\node_modules\lively-loader\index.js:155:14)
    at Object.withLivelyNamespaceDo (C:\Users\MartinRoberts\cloxp-0.2.0\LivelyKernel\node_modules\lively-loader\index.js:171:14)
    at loadNodejsLively (C:\Users\MartinRoberts\cloxp-0.2.0\LivelyKernel\bin\lk-server.js:205:30)
    at fn (C:\Users\MartinRoberts\cloxp-0.2.0\LivelyKernel\node_modules\async\lib\async.js:638:34)
    at Immediate.<anonymous> (C:\Users\MartinRoberts\cloxp-0.2.0\LivelyKernel\node_modules\async\lib\async.js:554:34)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by rksm** [comment]
This looks fixable, I'll take a look...
