### ISSUE TITLE
start.sh initiates infinite error loop

### ISSUE THREAD

**Issue by webappzero** [cloxp/cloxp-install#4]
I'm not able to get cloxp running on either OS X or Docker.

I can reproduce this bug  at will, consistently on both OS X 10.10.4 and the cloxp docker container by follwing the Cloxp installation instructions.

On final step: $ ./start.sh results in the following, repeating pattern of messages, which include multiple errors. By repeating, I mean that the Forever script keeps restarting the process, requiring ^C to interrupt.

I tried to extend the --minUptime setting to 100s by editing the option directly on line 267 of cli.js but this failed to correct the issue, which I'm still unable to ascertain the cause of.  My best guess so far is that has something to do with the error:`[2015-08-07 13:07:47.803] [ERROR] console - composeAsync:  'Error: Trying to get unknown option lively.Config.userAuthEnabled\n` but would appreciate your input. Thanks! (Also, thank you for Cloxp. Looks really cool!)

`$ ./start.sh
/Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel /Volumes/PRODATA/DATA/www/edu/clojure/cloxp
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
Checking if PartsBin exists...
...yes
[2015-08-07 13:07:47.713] [INFO] console - Lively server started with cross origin resource sharing (CORS) enabled.
Fri, 07 Aug 2015 17:07:47 GMT connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead at node_modules/life_star/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:56:20
Fri, 07 Aug 2015 17:07:47 GMT connect deprecated limit: Restrict request size at location of read at node_modules/life_star/node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15
[2015-08-07 13:07:47.803] [ERROR] console - composeAsync:  'Error: Trying to get unknown option lively.Config.userAuthEnabled\n    at Object.Global.Config.get (/Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/core/lively/defaultconfig.js:205:54)\n    at setupAuthHandler (/Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/life_star/life_star.js:266:42)\n    at /Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/lively.lang/lib/function.js:430:16\n    at next (/Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/lively.lang/lib/function.js:426:25)\n    at setupSSLCertHandler (/Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/life_star/life_star.js:259:5)\n    at /Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/lively.lang/lib/function.js:430:16\n    at next (/Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/lively.lang/lib/function.js:426:25)\n    at setupHTTPLogger (/Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/life_star/life_star.js:249:5)\n    at /Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/lively.lang/lib/function.js:430:16\n    at next (/Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/lively.lang/lib/function.js:426:25)'
[2015-08-07 13:07:47.805] [ERROR] console - Error starting life_star: Error: Trying to get unknown option lively.Config.userAuthEnabled
[2015-08-07 13:07:47.805] [INFO] console - Server with pid 19853 is now running at http://localhost:9001
[2015-08-07 13:07:47.805] [INFO] console - Serving files from /Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel
[2015-08-07 13:07:47.814] [INFO] console - Lively server starting...
error: Forever detected script exited with code: 0
error: Script restart attempt #1
Checking if PartsBin exists...
...yes
[2015-08-07 13:07:48.975] [INFO] console - Lively server started with cross origin resource sharing (CORS) enabled.
Fri, 07 Aug 2015 17:07:49 GMT connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead at node_modules/life_star/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:56:20
Fri, 07 Aug 2015 17:07:49 GMT connect deprecated limit: Restrict request size at location of read at node_modules/life_star/node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15
[2015-08-07 13:07:49.059] [ERROR] console - composeAsync:  'Error: Trying to get unknown option lively.Config.userAuthEnabled\n    at Object.Global.Config.get (/Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/core/lively/defaultconfig.js:205:54)\n    at setupAuthHandler (/Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/life_star/life_star.js:266:42)\n    at /Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/lively.lang/lib/function.js:430:16\n    at next (/Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/lively.lang/lib/function.js:426:25)\n    at setupSSLCertHandler (/Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/life_star/life_star.js:259:5)\n    at /Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/lively.lang/lib/function.js:430:16\n    at next (/Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/lively.lang/lib/function.js:426:25)\n    at setupHTTPLogger (/Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/life_star/life_star.js:249:5)\n    at /Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/lively.lang/lib/function.js:430:16\n    at next (/Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel/node_modules/lively.lang/lib/function.js:426:25)'
[2015-08-07 13:07:49.060] [ERROR] console - Error starting life_star: Error: Trying to get unknown option lively.Config.userAuthEnabled
[2015-08-07 13:07:49.060] [INFO] console - Server with pid 19858 is now running at http://localhost:9001
[2015-08-07 13:07:49.060] [INFO] console - Serving files from /Volumes/PRODATA/DATA/www/edu/clojure/cloxp/LivelyKernel
[2015-08-07 13:07:49.062] [INFO] console - Lively server starting...
error: Forever detected script exited with code: 0
error: Script restart attempt #2
Checking if PartsBin exists...
...yes`

**Comment by rksm** [comment]
Hi,

thanks for the bug report!

I updated the version of Lively used in cloxp-pre-0.0.8 to include the path for this issue (https://github.com/cloxp/LivelyKernel/commit/b99b2c19d2fae5e9d096a0c8e0fa0ef184a67f17).  The installation and start should now work as advertised.

Please let me know if you see other issues or want to give feedback.  I had to postpone development for cloxp for a while but getting back into it now.

Thanks,
Robert

**Comment by webappzero** [comment]
Thanks Robert! It's working.

Just a little feedback that might help newcomers have an easier time getting started:

Upon completion of running start.sh the final console message for me was: 

`LivelyFsHandler registerWith done`

This was followed, unceremoniously, by a flashing cursor. I was expecting a message with instructions on which port to open my browser to.

Opening my browser to localhost:9001 returned a webdav listing of files.

Clicking on cloxp.html got me into a working system. Please let me know if there's a better way. Should we include these extra steps in the cloxp-install readme?

**Comment by rksm** [comment]
Thanks, this stuff really isn't too clear.  I make emphasize it in the readme and will add an auto-browser launch inside start.sh.  Still dreaming of a hosted cloxp, though :)
